const express = require('express');
const router = express.Router();
const { verifyUserController, loginUserController, refreshUserController, logoutUserController } = require('../controllers/auth.controller');
const { validateUserAuth } = require('../validator/user.validator');
const { userAuthValidationMiddleware } = require('../middlewares/validator.middleware');
router.post('/verify',validateUserAuth,userAuthValidationMiddleware,verifyUserController);
router.post('/login',validateUserAuth,userAuthValidationMiddleware,loginUserController);
router.post('/refresh',refreshUserController);
router.post('logout',logoutUserController);
module.exports = router;